name: Publish

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Run tests
        run: cargo test

      - name: Login to crates.io
        run: cargo login ${CRATES_IO_API_KEY}
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

      - name: Publish on crates.io
        run: cargo publish
