name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Run tests
        run: cargo test

      - name: Publish on crates.io
        run: |
          cargo login ${CRATES_IO_API_KEY}
          cargo publish
        env:
          CRATES_IO_API_KEY: ${{ secrets.CRATES_IO_API_KEY }}
