name: Rust

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        run: cargo build --verbose
      - name: Docs
        run: cargo doc --verbose
      - name: Run tests
        run: cargo test --verbose
