name: Rust

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -f
          sudo apt-get install llvm-dev libclang-dev clang
          sudo apt-get install -f

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Docs
        run: cargo doc --verbose

      - uses: actions/upload-artifact@v1
        with:
          name: quest-rs-docs
          path: target/doc
